### ISSUE TITLE
using it in my router.ex

### ISSUE THREAD

**Issue by fariedt** [Zeeker/etag_plug#7]
_This is probably more of a Phoenix question than ETag.Plug..._

I created a new project using `mix phx.new hello`,  following the Phoenix 1.4.2 tutorial.  I tried changing the pipeline in `lib/hello_web/router.ex` to 
```
  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug ETag.Plug
  end
```
but that throws an error:
```
Request: GET /
** (exit) an exception was raised:
    ** (ArgumentError) could not fetch application environment :generator for application :etag_plug because configuration :generator was not set
        (elixir) lib/application.ex:490: Application.fetch_env!/2
        (elixir) lib/keyword.ex:606: Keyword.put_new_lazy/3
        (etag_plug) lib/etag/plug/options.ex:20: ETag.Plug.Options.sanitize!/1
        (hello) HelloWeb.Router.browser/2
[...]
```
Is there a central location where I can set my default configuration for ETag.Plug?  I would like to avoid copying
```
plug ETag.Plug, generator: ETag.Generator.SHA1, methods: ["GET"], status_codes: [:ok
```
into a bunch of pipelines.

**Comment by sascha-wolf** [comment]
You're right. I wrongly assumed that the `config.exs` would be included in the published hex package. Please update to version 0.2.0 which I just published.

**Comment by sascha-wolf** [comment]
To provide defaults you can just use (in your `config/config.exs` file):

```elixir
config :etag_plug,
  generator: YourDefaultHere,
  methods: ["GET", "HEAD"],
  status_codes: [200]
```

In the README the defaults used by the lib are also listed.
